# https://docs.microsoft.com/azure/devops/pipelines/yaml-schema

displayName: 'PR build and test'

pr:
- azure
- master
- release/*

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: build
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: test
    projects: '*Tests/*.csproj'
    arguments: '--configuration Release'